### PR TITLE
Added python script for processing response form

### PR DESCRIPTION
**Pull request by gurumukhi**
Added python script for processing response form.

About the script:
- Reads response file in csv & iterates through all entries with 'Y' in given range of rows.
- For every such row, it check if the name is already available in names.csv. If yes, prints the message that this name is ignored, else, it adds this name to the file.
- At the end it prints number of names added, email addresses to send email to, and commit message (the commit message includes name, email address and citation of all added rows).

### CODE REVIEW

**Comment by gerv** [comment]
Is there a reason the script does one commit rather than N commits? The previous script did N commits so that each person had their own commit message with their citation. I think this is better.

**Comment by gerv** [comment]
I also think it would be fine to have one directory called "scripts" with two files - check-names.pl and check-names.py. These need to be runnable from any directory, and find the "names.csv" file in the directory above their resident directory.

**Comment by gurumukhi** [comment]
Updated PR :
Put all scripts under one directory, fixed location of names.csv in perl script & added empty README.md in scripts to add useful info regarding scripts later.

Reason for single commit instead of one commit per name:
The consolidated commit will have names, emails & citations of all names added. No such reason for consolidated commit as such, but for now I am planning to check git diff manually I planned for consolidated commit (and then raise a PR). May be, we can switch to individual commits per name, once I start committing directly to the main repo without PR.

**Comment by gerv** [comment]
I would prefer to check in the scripts in one commit, and then do the names in a separate series of commits. We've been doing one commit per name since the beginning, pretty consistently, and it would be a shame to break that now. If Github makes that harder to review, is that a problem with the Github UX?

**Comment by gurumukhi** [comment]
@gerv I updated the script to incorporate the changes, kindly review. 

* Now the script is making N commits for N names additions.
* Scripts are under single directory.
* Documentation added in README file.

**Pull request merged**
