### PR TITLE
Add Indonesian localizers to names.csv

### PR DESCRIPTION
**Pull request by twse**
Add Indonesian localizers and fix sort key for Dody Suria Wijaya. Sourced from [this](http://web.archive.org/web/20081224033440/http://www.mountbromo.com/tech/mozilla/mozilla-id.html), [this](https://bugzil.la/280249) and [this](https://bugzil.la/328651).
- Daniel W. Howard
- Adi D. Jayanto
- Endro Koesno
- Albert Sutojo
- Martin Tedjawardhana

### CODE REVIEW

**Comment by gurumukhi** [comment]
As per the Mozilla's policy (https://www.mozilla.org/credits/faq/) we accept names only through the form mentioned on the credits page. If the sort key or name is incorrect for someone, he/she will have to reply to the mail which was sent to inform him/her about the addition of the name.

**Comment by twse** [comment]
Never mind, I added these names using the form instead and sent a mail to gurumukhi and gurumukhi needs to get this pull request merged.

**Comment by gerv** [comment]
@twse Please do not fill in the form on behalf of anyone else. People should fill in the form for themselves.

**Comment by twse** [comment]
Created commit to add names - 7c5758fc.

**Pull request closed without merging**
