### PR TITLE
Add Slovak localizers to names.csv

### PR DESCRIPTION
**Pull request by twse**
Sourced from [this page](http://web.archive.org/web/20071229005852/http://www.mozilla.sk:80/o-nas/), in Slovak only / len v Slovenský.
* Andrej Macko – Mozilla 0.9.1 l10n (Slovak)
* Branislav Pavelka – Mozilla Europe website, administrator and designer of Mozilla Europe portal, module programmer for WordPress
* Ján Gallik (Gianny111) – L10n: Slovak
* Ján Kendi (Jacen) – L10n: Slovak
* Ján Letko – Calendar, Sunbird and Enigmail l10n (Slovak)
* Jozef Remeň – Camino l10n (Slovak) and Firefox/Thunderbird QA tester on macOS
* Michal Adamec (Emsy) – Mozilla Suite and SeaMonkey localization helper (Slovak)
* Peter Macej – Firefox 1.0 l10n (Slovak)
* Peter Mikšík (SlovakSoft) – Translator and proofreader for Slovak, Mozilla Add-ons, MozBackup, Songbird, XULPlayer localizer, supporter and Mozilla.sk forum administrator
* Radovan Bukóci – Mozilla Suite 1.x, Netscape 7.x SeaMonkey, mozilla.sk portal translator (Slovak)
* Roland Turčan – Mozilla 1.0 and Mozilla Europe site l10n (Slovak)
* Stanislav Višňovský – Mozilla 0.9.1 l10n (Slovak)
* Zdenko Podobný – Slovak dictionary and tester for Thunderbird, Mozilla Suite, SeaMonkey and Nvu

Not listed:
* Jiří Šebesta – Netscape L10n (cs, sk)
* Pavol Vaškovič – Tech Evangelism
* Peter Kolesár – L10n: Slovak
* Peter Ondráška – Thunderbird developer and localizer (Slovak)
* Slavomír Čéplö – Mozilla l10n (Eastern Slovak)

### CODE REVIEW

**Comment by gurumukhi** [comment]
As per the Mozilla's policy (https://www.mozilla.org/credits/faq/) we accept names only through the form mentioned on the credits page.

**Comment by twse** [comment]
I vote for Branislav Rozbora to reopen and merge the pull request.

**Comment by aceman444** [comment]
Hi, what is this about? Where did you get permission to collect the names and put into any file? Also, the patch contains more names than what is at https://www.mozilla.sk/o-nas/ so where did you get them from?
I object to my name being publicly visible to this day at https://github.com/mozilla/community-data/pull/12/files, please arrange for hiding that patch in all history of this github project immediately.
Thanks.

**Comment by twse** [comment]
Hi Peter.

I did not get permission to collect the names and put it into [this file](https://github.com/twse/random-stuff/blob/master/names.csv). I got the remaining names from the first comment.

Reopening and merging the pull request can only be done when you're logged in as @gurumukhi (the pull request was closed but I reacted on the comment).

**Comment by aceman444** [comment]
"Thanks" for publishing the name again in a comment. Please hide the comment contents soon.

I alredy got the name pulled from about:credits in Firefox, I request it be removed from other files like the names.csv (looks like you already did it) and also from all these github comments and commit history.

Thanks for confirming the names are collected without permission, .

**Pull request closed without merging**
